#FROM envoyproxy/envoy-alpine-dev:latest
# App Mesh Envoy version

FROM envoyproxy/envoy-alpine:v1.12.3

RUN apk update && apk add python3 bash curl
RUN pip3 install --upgrade pip
RUN pip3 install -q Flask==0.11.1 requests==2.18.4
RUN mkdir /code
ADD ./service.py /code
ADD ./start_service.sh /usr/local/bin/start_service.sh
RUN chmod u+x /usr/local/bin/start_service.sh
ENTRYPOINT /usr/local/bin/start_service.sh