version: "3.7"
services:

  # Zipkin
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    networks:
      envoymesh:
        aliases:
          - zipkin-all-in-one    
    ports:
      - "9400:9411" # host_port:container_port. host_port is accessible from the host on the Docker IP/localhost

  # Collector
  # docker run -it --entrypoint /bin/bash otel/opentelemetry-collector-contrib:latest -s "--config=/etc/otel-collector-config.yaml"
  otel-collector:
    build:
      context: ../../otel-collector/collector-contrib
      dockerfile: dockerfile
    
    volumes:
     - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    networks:
      envoymesh:
        aliases:
          - otel-collector
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "55678"       # OpenCensus receiver
      - "55680:55679" # zpages extension
      - "9090"        # OTel protocol (otlp) receiver
    depends_on:
      #- jaeger-all-in-one
      - zipkin-all-in-one

networks:
  envoymesh: {}