FROM otel/opentelemetry-collector-contrib:latest
# bake an image with our config file becasue it's a pain to pass in at runtime with AWS Fargate
COPY ./otel-collector-config.yaml /etc/otel-collector-config.yaml

# ENTRYPOINT exec name and EXPOSEports copied from base image dockerfile
# https://github.com/open-telemetry/opentelemetry-collector/blob/master/cmd/otelcol/Dockerfile
ENTRYPOINT ["/otelcontribcol", "--config=/etc/otel-collector-config.yaml"]

# 1888  - pprof extension
# 8888  - Prometheus metrics exposed by the collector
# 8889  - Prometheus exporter metrics
# 13133 - health_check extension
# 55678 - OpenCensus receiver
# 55679 - zpages extension
# 9090  - OTel protocol (otlp) receiver default
EXPOSE 1888 8888 8889 13133 55678 55679 9090